utils::globalVariables(c("FloorDate", 
                         "Week", 
                         "NumClosed",
                         "Priority",
                         "Created",
                         "Closed",
                         "Updated",
                         "cldt",
                         "crdt"
                         ))
